// Z160: PORT mapy nazw EN z src/data/exercise-i18n.ts — digest mailowy tłumaczy
// nazwy ćwiczeń dla userów EN. Spójność z klientem pilnuje test
// src/test/exercise-i18n-coverage.test.ts (porównanie obu map 1:1).

export const EXERCISE_NAME_EN: Record<string, string> = {
  "Wyciskanie sztangi na ławce płaskiej": "Barbell Bench Press",
  "Wyciskanie hantli na ławce płaskiej": "Dumbbell Bench Press",
  "Wyciskanie hantli (Lekki skos)": "Incline Dumbbell Press (Slight Incline)",
  "Wyciskanie sztangi na skosie": "Incline Barbell Press",
  "Rozpiętki hantlami": "Dumbbell Flyes",
  "Rozpiętki na lince (Crossover)": "Cable Crossover",
  "Pompki": "Push-ups",
  "Wyciskanie w maszynie": "Machine Chest Press",
  "Wiosłowanie sztangą": "Barbell Row",
  "Wiosłowanie hantlami na ławce (przodem)": "Chest-Supported Dumbbell Row",
  "Wiosłowanie hantlem jednorącz (Laty)": "One-Arm Dumbbell Row (Lats)",
  "Ściąganie drążka (Szeroki nachwyt)": "Lat Pulldown (Wide Grip)",
  "Ściąganie drążka (Wąski nachwyt)": "Lat Pulldown (Close Grip)",
  "Podciąganie na drążku": "Pull-Up",
  "Wiosłowanie na lince siedząc": "Seated Cable Row",
  "Pullover na lince": "Cable Pullover",
  "Wyciskanie hantli nad głowę (Siedząc)": "Seated Dumbbell Shoulder Press",
  "Wyciskanie sztangi nad głowę (OHP)": "Overhead Press (OHP)",
  "Wznosy bokiem (Lateral Raise)": "Lateral Raise",
  "Wznosy bokiem leżąc (Y-Raise)": "Incline Y-Raise",
  "Odwrotne rozpiętki (Tył barku)": "Reverse Fly (Rear Delt)",
  "Face Pull": "Face Pull",
  "Arnoldki": "Arnold Press",
  "Przysiad ze sztangą (High Bar)": "Barbell Squat (High Bar)",
  "Przysiad ze sztangą (Low Bar)": "Barbell Squat (Low Bar)",
  "Przysiad goblet": "Goblet Squat",
  "Prasa nożna": "Leg Press",
  "Wyprosty nóg na maszynie": "Leg Extension",
  "Wykroki chodzone": "Walking Lunges",
  "Wykroki bułgarskie": "Bulgarian Split Squat",
  "Martwy Ciąg Rumuński (RDL)": "Romanian Deadlift (RDL)",
  "Martwy ciąg klasyczny": "Conventional Deadlift",
  "Uginanie nóg na maszynie (Siedząc)": "Seated Leg Curl",
  "Uginanie nóg na maszynie (Leżąc)": "Lying Leg Curl",
  "Good Morning": "Good Morning",
  "Hip Thrust (Wypychanie bioder)": "Hip Thrust",
  "Hip Thrust ze sztangą": "Barbell Hip Thrust",
  "Odwodzenie na lince": "Cable Hip Abduction",
  "Glute Bridge": "Glute Bridge",
  "Uginanie hantli z supinacją (Ławka skośna)": "Incline Dumbbell Curl (Supination)",
  "Uginanie sztangi stojąc": "Standing Barbell Curl",
  "Uginanie na lince (Hammer)": "Cable Hammer Curl",
  "Uginanie hantli hammer": "Hammer Curl",
  "Wyprosty francuskie zza głowy": "Overhead Dumbbell Triceps Extension",
  "Wyprosty na lince (Pushdown)": "Triceps Pushdown",
  "Dips (pompki na poręczach)": "Dips",
  "Skull Crushers": "Skull Crushers",
  "Dead Bug (Robak - Brzuch)": "Dead Bug",
  "Plank": "Plank",
  "Ab Rollout": "Ab Rollout",
  "Unoszenie nóg w zwisie": "Hanging Leg Raise",
  "Skręty rosyjskie": "Russian Twists",
  "Modlitewnik (Cable Crunch)": "Cable Crunch",
  "Reverse Crunch na ławce": "Bench Reverse Crunch",
  "Wspięcia na palce (Nogi proste)": "Leg Press Calf Raise (Straight Leg)",
  "Wspięcia na palce siedząc": "Seated Calf Raise",
  "Wyciskanie na maszynie Hammer": "Hammer Strength Chest Press",
  "Pec Deck (Butterfly)": "Pec Deck (Butterfly)",
  "Otwieranie klatki hantlami": "Dumbbell Chest Opener",
  "Wiosłowanie na maszynie (Hammer)": "Hammer Strength Row (Machine)",
  "Wiosłowanie T-bar": "T-Bar Row",
  "Wiosłowanie Pendleya": "Pendlay Row",
  "Podciąganie na drążku podchwytem": "Chin-Up",
  "Ściąganie linki prostymi ramionami": "Straight-Arm Cable Pulldown",
  "Przenoszenie hantla za głowę": "Dumbbell Pullover",
  "Szrugi ze sztangą": "Barbell Shrugs",
  "Szrugi z hantlami": "Dumbbell Shrugs",
  "Prostowniki grzbietu (Hyperextensions)": "Back Extensions (Hyperextensions)",
  "Wyciskanie nad głowę na maszynie": "Machine Shoulder Press",
  "Wznosy bokiem na maszynie": "Machine Lateral Raise",
  "Wznosy bokiem na wyciągu": "Cable Lateral Raise",
  "Wznosy bokiem na lince (zza pleców)": "Behind-the-Back Cable Lateral Raise",
  "Rotacje ramienia z gumą frontem": "Band External Rotation (Front)",
  "Aniołki i demony": "Prone Angels and Demons",
  "Wall Angel": "Wall Angel",
  "Rozciąganie gumy nad głową": "Overhead Band Pull-Apart",
  "Hack Squat (maszyna)": "Hack Squat (Machine)",
  "Wyciskanie jednonóż na suwnicy": "Single-Leg Press (Smith Machine)",
  "Sissy Squat": "Sissy Squat",
  "Przywodziciele na maszynie": "Hip Adduction Machine",
  "Cossack Squat": "Cossack Squat",
  "Przysiady wykroczne": "Forward Lunges",
  "Zakroki sprinterskie": "Sprinter Reverse Lunges",
  "Wejścia bokiem na skrzynię": "Lateral Box Step-Ups",
  "Odwodziciele na maszynie": "Hip Abduction Machine",
  "Glute Kickback na wyciągu": "Cable Glute Kickback",
  "Pull Through": "Cable Pull Through",
  "Wyprosty biodra z gumą": "Banded Hip Extension",
  "Uginanie na modlitewniku (Preacher)": "Preacher Curl",
  "Uginania ze sztangą na modlitewniku": "Preacher Barbell Curl",
  "Uginania łokci z hantlami stojąc": "Standing Dumbbell Curl",
  "Uginanie na wyciągu dolnym": "Low Cable Curl",
  "Uginanie na maszynie": "Machine Curl",
  "Wyciskanie wąsko (Close-grip)": "Close-Grip Bench Press",
  "Francuskie wyciskanie sztangi leżąc": "Lying Barbell Triceps Extension",
  "Wyciskanie hantla oburącz w klęku": "Two-Handed Overhead Dumbbell Extension",
  "Triceps na maszynie": "Machine Triceps Extension",
  "Kickback z hantlą": "Dumbbell Kickback",
  "Brzuszki na maszynie": "Machine Crunch",
  "Pallof Press": "Pallof Press",
  "Cable Woodchopper": "Cable Woodchopper",
  "Mountain Climbers": "Mountain Climbers",
  "Hollow Hold": "Hollow Hold",
  "Wspięcia na palce na suwnicy": "Smith Machine Calf Raise",
  "Wspięcia na maszynie stojąc": "Standing Calf Raise (Machine)",
  "Donkey Calf Raise": "Donkey Calf Raise",
  "Wyciskanie sztangi na ławce ujemnej (deklina)": "Decline Barbell Bench Press",
  "Wyciskanie hantli na ławce ujemnej (deklina)": "Decline Dumbbell Bench Press",
  "Wyciskanie na Smith maszynie (ławka skośna)": "Smith Machine Incline Press",
  "Wyciskanie na Smith maszynie (ławka płaska)": "Smith Machine Flat Press",
  "Wyciskanie na maszynie Hammer (skos góra)": "Hammer Strength Incline Press",
  "Wyciskanie na maszynie Hammer (skos dół)": "Hammer Strength Decline Press",
  "Dipy na poręczach (na klatkę)": "Chest Dips",
  "Dipy z obciążeniem (na klatkę)": "Weighted Chest Dips",
  "Rozpiętki na wyciągu z dołu (góra klatki)": "Low Cable Fly (Upward)",
  "Rozpiętki na wyciągu z góry (dół klatki)": "High Cable Fly (Downward)",
  "Wyciskanie na wyciągu stojąc (góra klatki)": "Standing Cable Chest Press",
  "Svend Press (ściskanie talerzy)": "Svend Press",
  "Wyciskanie hantli wąsko (chwyt neutralny)": "Neutral Grip Dumbbell Press (Squeeze Press)",
  "Rozpiętki gumą oporową stojąc": "Resistance Band Chest Fly",
  "Pompki na podwyższeniu (nogi w górze)": "Decline Push-Up (Feet Elevated)",
  "Pompki diamentowe": "Diamond Push-Up",
  "Ściąganie drążka podchwytem (wąsko)": "Underhand Lat Pulldown",
  "Ściąganie drążka neutralnym chwytem": "Neutral-Grip Lat Pulldown",
  "Podciąganie wspomagane na maszynie": "Assisted Pull-Up Machine",
  "Spacer farmera (Farmer's Walk)": "Farmer's Walk",
  "Dipy wspomagane na maszynie": "Assisted Dip Machine",
  "Wiosłowanie T-bar wąskim chwytem (uchwyt V)": "Close-Grip T-Bar Row",
  "Wiosłowanie na maszynie jednorącz (plate-loaded)": "Single-Arm Plate-Loaded Row",
  "Wiosłowanie w podporze na ławce skośnej (chest-supported)": "Chest-Supported Dumbbell Row",
  "Wiosłowanie Meadowsa": "Meadows Row",
  "Martwy ciąg częściowy z podstawek (Rack Pull)": "Rack Pull",
  "Wiosłowanie w maszynie Smitha": "Smith Machine Bent-Over Row",
  "Australijskie podciąganie (Inverted Row)": "Inverted Row",
  "Szrugi w maszynie Smitha": "Smith Machine Shrug",
  "Szrugi na wyciągu": "Cable Shrug",
  "Pullover na maszynie": "Machine Pullover",
  "Wiosłowanie na lince stojąc (Face Pull do twarzy)": "Cable Face Pull",
  "Martwy ciąg sumo (akcent na plecy)": "Sumo Deadlift",
  "Martwy ciąg z deficytu": "Deficit Deadlift",
  "Wymachy kettlebell (posterior chain)": "Kettlebell Swing",
  "Wyciskanie barków na maszynie Hammer Strength (jednorącz)": "Hammer Strength Shoulder Press (Unilateral)",
  "Wyciskanie nad głowę w Smith (Smith OHP)": "Smith Machine Overhead Press",
  "Odwrotne rozpiętki na maszynie (Reverse Pec Deck)": "Reverse Pec Deck",
  "Wznosy bokiem jednorącz na wyciągu dolnym": "Single-Arm Cable Lateral Raise",
  "Podciąganie sztangi wzdłuż tułowia (Upright Row)": "Barbell Upright Row",
  "Podciąganie wzdłuż tułowia na wyciągu (Cable Upright Row)": "Cable Upright Row",
  "Podciąganie hantli wzdłuż tułowia (Dumbbell Upright Row)": "Dumbbell Upright Row",
  "Cuban Press (rotacja zewnętrzna z wyciskaniem)": "Cuban Press",
  "Z-Press (wyciskanie siedząc na podłodze)": "Seated Z-Press",
  "Landmine Press (wyciskanie jednorącz)": "Single-Arm Landmine Press",
  "Pompki w pozycji szczytowej (Pike Push-up)": "Pike Push-up",
  "Wyciskanie hantli neutralnym chwytem nad głowę": "Neutral-Grip Dumbbell Shoulder Press",
  "Wznosy bokiem z gumą oporową": "Resistance Band Lateral Raise",
  "Wznosy sztangi w przód (Barbell Front Raise)": "Barbell Front Raise",
  "Wznosy krążka w przód (Plate Front Raise)": "Plate Front Raise",
  "Wznosy 6-kierunkowe (6-Way Raise)": "Dumbbell 6-Way Raise",
  "Przysiad przedni ze sztangą (Front Squat)": "Front Squat",
  "Prasa nożna pozioma (siedząc)": "Horizontal Leg Press",
  "Prasa nożna pionowa (leżąc)": "Vertical Leg Press",
  "Hack Squat odwrotny (twarzą do oparcia)": "Reverse Hack Squat",
  "Pendulum Squat (maszyna wahadłowa)": "Pendulum Squat",
  "Przysiad Belt Squat (z pasem biodrowym)": "Belt Squat",
  "Wyprosty nóg na maszynie jednonóż": "Single-Leg Leg Extension",
  "Uginanie nóg stojąc jednonóż na maszynie": "Standing Single-Leg Curl",
  "Przysiad w suwnicy Smitha": "Smith Machine Squat",
  "Wykrok w suwnicy Smitha": "Smith Machine Lunge",
  "Glute-Ham Raise (GHR)": "Glute-Ham Raise",
  "Nordic Hamstring Curl": "Nordic Hamstring Curl",
  "Przysiad pistolet (jednonóż)": "Pistol Squat",
  "Przysiad z masą ciała (Air Squat)": "Air Squat",
  "Sissy Squat na maszynie": "Machine Sissy Squat",
  "Wejścia przodem na skrzynię ze sztangielkami": "Dumbbell Step-Up",
  "Przysiad do skrzyni (Box Squat)": "Box Squat",
  "Przysiad Zercher (sztanga w zgięciach łokci)": "Zercher Squat",
  "Przysiad sumo z kettlebell": "Kettlebell Sumo Squat",
  "Wykroki chodzone z hantlami (długi krok)": "Long-Stride Dumbbell Walking Lunge",
  "Wypychanie bioder na maszynie Glute Drive": "Glute Drive Machine Hip Thrust",
  "Hip Thrust w maszynie Smith": "Smith Machine Hip Thrust",
  "Odwodzenie ud na maszynie z pochyleniem tułowia": "Leaning Hip Abductor Machine",
  "Kickback pośladka na maszynie": "Glute Kickback Machine",
  "Przeciąganie linki między nogami (Cable Pull-Through)": "Cable Pull-Through",
  "Mostek pośladkowy na jednej nodze": "Single-Leg Glute Bridge",
  "Frog Pump (mostek z rozłożonymi kolanami)": "Frog Pump",
  "Wykrok ukośny (Curtsy Lunge)": "Curtsy Lunge",
  "Wysoki step-up z hantlami": "High Box Step-Up",
  "Wykrok w tył z akcentem na pośladek": "Reverse Lunge (Glute Focus)",
  "Rumuński martwy ciąg z akcentem na pośladek": "Romanian Deadlift (Glute Focus)",
  "Wymachy kettlebell": "Kettlebell Swing",
  "Kickback pośladka z gumą oporową": "Banded Donkey Kick",
  "Hip Thrust w rozstawie B-stance": "B-Stance Hip Thrust",
  "Uginanie skoncentrowane (Concentration Curl)": "Concentration Curl",
  "Uginanie na pająku (Spider Curl)": "Spider Curl",
  "Uginanie z dociąganiem (Drag Curl)": "Drag Curl",
  "Uginanie bayesowskie na wyciągu (Bayesian Cable Curl)": "Bayesian Cable Curl",
  "Uginanie hantli na ławce skośnej (Incline Curl)": "Incline Dumbbell Curl",
  "Uginanie Zottmana (Zottman Curl)": "Zottman Curl",
  "Uginanie ramion na maszynie wyciąg jednorącz (Single-Arm Cable Curl)": "Single-Arm Cable Curl",
  "Uginanie odwrotne (Reverse Curl)": "Reverse Barbell Curl",
  "Uginanie 21-tki (21s)": "Barbell Curl 21s",
  "Prostowanie ramion zza głowy na wyciągu (Overhead Cable Extension)": "Overhead Cable Triceps Extension",
  "Prostowanie ramion z liną na wyciągu (Rope Pushdown)": "Triceps Rope Pushdown",
  "Prostowanie ramienia na wyciągu jednorącz (Single-Arm Pushdown)": "Single-Arm Cable Pushdown",
  "JM Press (wyciskanie JM)": "JM Press",
  "Tate Press (wyciskanie Tate)": "Tate Press",
  "Dipy na maszynie (Assisted Dip Machine)": "Machine Triceps Dip",
  "Pompki diamentowe (Diamond Push-up)": "Diamond Push-up",
  "Dipy na ławce (Bench Dips)": "Bench Dips",
  "Prostowanie ramion zza głowy z hantlą oburącz (Overhead DB Extension)": "Overhead Dumbbell Triceps Extension",
  "Uginanie nadgarstków ze sztangą (Wrist Curl)": "Barbell Wrist Curl",
  "Odwrotne uginanie nadgarstków ze sztangą (Reverse Wrist Curl)": "Reverse Barbell Wrist Curl",
  "Izometryczny chwyt farmera (Farmer's Hold)": "Farmer's Hold",
  "Uginanie hammer na wyciągu z liną (Cable Rope Hammer Curl)": "Cable Rope Hammer Curl",
  "Wyciskanie wąsko w maszynie Smitha (Smith Close-Grip Press)": "Smith Machine Close-Grip Bench Press",
  "Brzuszki klasyczne (Crunch)": "Crunch",
  "Pełne spięcie brzucha (Sit-up)": "Sit-up",
  "Brzuszki rowerek (Bicycle Crunch)": "Bicycle Crunch",
  "Plank boczny (Side Plank)": "Side Plank",
  "Hollow Rock (Bujanie w łódce)": "Hollow Rock",
  "V-up (Scyzoryk)": "V-up",
  "Nogi do drążka (Toes to Bar)": "Toes to Bar",
  "Unoszenie kolan w zwisie": "Hanging Knee Raise",
  "Wyciskanie kółka do brzucha z klęku jednorącz": "Single-Arm Ab Wheel Rollout",
  "Spięcia brzucha na ławce skośnej (Decline Sit-up)": "Decline Sit-up",
  "Modlitewnik klęczący jednostronny (Cable Crunch)": "Kneeling Single-Side Cable Crunch",
  "Wysoki Woodchopper na wyciągu (z dołu do góry)": "Low-to-High Cable Woodchopper",
  "Dead Bug z hantlami (obciążony)": "Weighted Dead Bug",
  "Pallof Press w przysiadzie (warianty)": "Pallof Press in Half-Squat",
  "Dragon Flag (Flaga Smoka)": "Dragon Flag",
  "L-sit (Podpór kątowy)": "L-sit",
  "Plank z dotykaniem barków": "Plank Shoulder Taps",
  "Superman (Unoszenie tułowia leżąc na brzuchu)": "Superman",
  "Burpees": "Burpees",
  "Wspięcia na palce na prasie nożnej (Leg Press)": "Leg Press Calf Raise",
  "Wspięcia na palce w maszynie Smitha (stojąc)": "Smith Machine Standing Calf Raise",
  "Wspięcia na palce jednonóż z hantlą": "Single-Leg Dumbbell Calf Raise",
  "Wspięcia na palce ze sztangą stojąc": "Standing Barbell Calf Raise",
  "Wspięcia na palce jednonóż na podwyższeniu (masa ciała)": "Single-Leg Bodyweight Calf Raise on Step",
  "Wznosy palców na piszczel (Tibialis Raise)": "Tibialis Raise",
  "Skakanka jako trening łydek": "Jump Rope for Calves",
  "Wspięcia na palce z kettlebell stojąc": "Standing Kettlebell Calf Raise",
  "Wspięcia na palce na hack squacie": "Hack Squat Calf Raise",
  "Wspięcia na palce na suwnicy siedząc (zgięte kolana)": "Seated Smith Machine Calf Raise",
  // Z156: nazwy z domyślnego planu i szablonów (planTemplates), które nie miały wpisu —
  // pilnowane testem inwentarzowym exercise-i18n-coverage.test.ts.
  "Przysiad ze sztangą": "Barbell Squat",
  "Przysiady bułgarskie": "Bulgarian Split Squat",
  "Wyciskanie sztangi na ławce poziomej": "Flat Barbell Bench Press",
  "Rozpiętki na ławce poziomej": "Flat Bench Dumbbell Flyes",
  "Wyciskanie hantli siedząc": "Seated Dumbbell Shoulder Press",
  "Martwy ciąg ze sztangą": "Barbell Deadlift",
  "Wiosłowanie hantlą w opadzie": "Bent-Over Dumbbell Row",
  "Pompki na poręczach": "Dips",
  "Wyciskanie hantla po skosie w górę": "Incline Dumbbell Press",
  "OHP": "Overhead Press",
  "Uginania łokci ze sztangą stojąc": "Standing Barbell Curl",
  "Uginania młotkowe hantlą": "Dumbbell Hammer Curl",
  "AMRAP: swing/pompki/bike": "AMRAP: Swings/Push-ups/Bike",
  "Air bike / farmer walk": "Air Bike / Farmer's Walk",
  "Cable curl / modlitewnik": "Cable Curl / Preacher Curl",
  "Cable pullover / straight-arm pulldown": "Cable Pullover / Straight-Arm Pulldown",
  "Core: dead bug / plank RKC": "Core: Dead Bug / RKC Plank",
  "Face pull z rotacja": "Face Pull with External Rotation",
  "Machine/cable lateral raise": "Machine/Cable Lateral Raise",
  "Podciaganie nachwytem": "Overhand Pull-Up",
  "Przysiad tylny": "Back Squat",
  "RDL - martwy rumunski": "Romanian Deadlift (RDL)",
  "Reverse pec deck / rear delt fly": "Reverse Pec Deck / Rear Delt Fly",
  "Sciaganie drazka neutralnie": "Neutral-Grip Lat Pulldown",
  "Ski erg / sled / farmer": "Ski Erg / Sled / Farmer's Walk",
  "Trap bar deadlift / Front squat": "Trap Bar Deadlift / Front Squat",
  "Unoszenie bokiem linka/hantle": "Lateral Raise (Cable/Dumbbell)",
  "Wioslowanie chest-supported": "Chest-Supported Row",
  "Wyciskanie hantli siedzac / landmine": "Seated Dumbbell Press / Landmine Press",
  "Wyciskanie sztangi lezac": "Barbell Bench Press",
};

export const localizeExerciseNameEn = (name: string): string => EXERCISE_NAME_EN[name] ?? name;
